spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/api-pessoas?createDatabaseIfNotExist=true
    username: root
    password: root
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com                  # Endereço do servidor SMTP
    port: 587                             # Porta do servidor SMTP
    username: seu email   # Usuário do servidor SMTP
    password: sua senha         # Senha do servidor SMTP
    protocol: smtp                        # Protocolo SMTP (pode ser smtp, smtps ou smtps)
    properties:
      mail:
        smtp:
          auth: true                      # Ativar autenticação SMTP
          starttls:
            enable: true                  # Habilitar STARTTLS para criptografia
            required: true                # Requer STARTTLS
          ssl:
            trust: smtp.gmail.com         # Confiar no servidor SMTP (pode ser o mesmo que o host)

server:
  port: 8080
  servlet:
    context-path: /api
---

spring:
  config:
    activate:
      on-profile: homolog
  datasource:
    url: jdbc:mysql://localhost:3306/api-pessoas-homolog?createDatabaseIfNotExist=true
    username: root
    password: root
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com                  # Endereço do servidor SMTP
    port: 587                             # Porta do servidor SMTP
    username: seu email   # Usuário do servidor SMTP
    password: sua senha         # Senha do servidor SMTP
    protocol: smtp                        # Protocolo SMTP (pode ser smtp, smtps ou smtps)
    properties:
      mail:
        smtp:
          auth: true                      # Ativar autenticação SMTP
          starttls:
            enable: true                  # Habilitar STARTTLS para criptografia
            required: true                # Requer STARTTLS
          ssl:
            trust: smtp.gmail.com         # Confiar no servidor SMTP (pode ser o mesmo que o host)


server:
  port: 8081
  servlet:
    context-path: /api